### PR TITLE
Cryomech CPA Agent Cleanup

### PR DESCRIPTION
**Pull request by gdevenyi**
Implement a number of changes to Cryomech agent
- uniformize conversion using struct.unpack for big-endian data
- add additional outputs
- add lookup table for status codes -- note, "-2147483648" is returned from my device under no warning/error condition, rather than 0
- renamed fields according to the cryomech manual

I took cryomech_cpa_agent.py and wrote a standalone version for my monitoring systems. This is a backport of the changes I made during my quest to understand the data returned from the device. These changes have not been tested in the context of "socs"

### CODE REVIEW

**Comment by JakeSpisak** [comment]
Hey Gabriel, thanks for doing this! I had just written code to turn the compressor on/off, and on my to-do list before pushing was adding in the status code and warning meanings. So if you want, I can take your changes, add my compressor on/off functionality, test in socs, and then take this draft pull request to a full pull request

**Comment by gdevenyi** [comment]
Sounds good to me. I got in contact today with cryomech regarding "Alarms" and "Errors', hopefully they'll get back to me.

I've also added the Model code lookup, and from the updated cryomech documentation a register for "Software Revision", however it also doesn't return anything meaningful (yet).  I'll push my additional changes onto the PR.

**Comment by JakeSpisak** [comment]
Sounds good. I got in contact with cryomech a while back, and they gave me [this code](https://drive.google.com/file/d/1BQAEDAk2KwH_uNDbT6NjFO0rqJ3BvViY/view?usp=sharing)  they were using to develop a gui. I think it has most of the information we want regarding warnings and alarms, but I haven't looked through it in detail. Also just as a heads up, the last time I contacted cryomech there was a ~1 week delay in the reply, and someone said that some members of their team have only sporadic email access.

**Comment by gdevenyi** [comment]
Thanks @JakeSpisak that code confirms a suspicion I had, that the warnings and alarm states are a bitmask rather than being a single state. Sadly the implementation is very silly, storing the integer representation of a bitmask as a FLOAT instead of storing as a 32bit bitmask so you could just do bitwise operations to test it.

What's also interesting is I see some status codes that are not documented the PDF they shared. I'll add those to my lookup table.

**Comment by gdevenyi** [comment]
I haven't had time to port my code back into the socs version, but here's my version, its now "complete" given the feedback I got from Cryomech
```python
#!/usr/bin/env python3
# Script to readout PTC data through ethernet connection.
# Originaly from socs project
# https://github.com/simonsobs/socs
# Tamar Ervin and Jake Spisak, February 2019
# Modifications by Gabriel A. Devenyi <gabriel.devenyi@mcgill.ca>
# 2020-04
# - make standalone command line
# - add lookup tables on status codes
# - make number conversion uniform using struct.unpack
# BSD 2-Clause "Simplified" License

import os
import argparse
import time
import struct
import socket
import signal
import datetime


class TimeoutException(Exception):
    pass


def time_limit(seconds):
    def signal_handler(signum, frame):
        raise TimeoutException("Timed out!")

    signal.signal(signal.SIGALRM, signal_handler)
    signal.alarm(seconds)
    try:
        yield
    finally:
        signal.alarm(0)


class PTC:
    def __init__(self, ip_address, port=502, timeout=10):
        self.ip_address = ip_address
        self.port = port

        self.comm = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.comm.connect((self.ip_address, self.port))  # connects to the PTC
        self.comm.settimeout(timeout)

    def get_data(self):
        """
        Gets the raw data from the ptc and returns it in a usable format.
        """
        self.comm.sendall(self.buildRegistersQuery())
        data = self.comm.recv(1024)
        data_flag, brd = self.breakdownReplyData(data)

        return data_flag, brd

    def buildRegistersQuery(self):
        # ModBusTCP query code
        query = bytes(
            [
                0x09, 0x99,  # Message ID (arbitrary)
                0x00, 0x00,  # Protocol Identifier
                0x00, 0x06,  # Message size to follow (bytes)
                0x01,  # Unit Identifier
                0x04,  # Read Analog Input Register
                0x00, 0x01,  # Starting Register
                0x00, 0x35,  # Number of 2 byte registers to read
            ]
        )
        return query

    def breakdownReplyData(self, rawdata):
        """
        Take in raw ptc data, and return a dictionary.
        The dictionary keys are the data labels,
        the dictionary values are the data in floats or ints.
        """

        # Associations between keys and their location in rawData
        # Original data as transmitted is high byte first, low word first
        # We rearrange to do high byte first, high word first which is "big endian"
        keyloc = {"Operating State": [9, 10],
                  "Compressor State": [11, 12],
                  "Warning State": [15, 16, 13, 14],
                  "Alarm State": [19, 20, 17, 18],
                  "Coolant In Temp": [23, 24, 21, 22],
                  "Coolant Out Temp": [27, 28, 25, 26],
                  "Oil Temp": [31, 32, 29, 30],
                  "Helium Temp": [35, 36, 33, 34],
                  "Low Pressure": [39, 40, 37, 38],
                  "Low Pressure Average": [43, 44, 41, 42],
                  "High Pressure": [47, 48, 45, 46],
                  "High Pressure Average": [51, 52, 49, 50],
                  "Delta Pressure Average": [55, 56, 53, 54],
                  "Motor Current": [59, 60, 57, 58],
                  "Hours of Opperation": [63, 64, 61, 62],
                  "Pressure Unit": [65, 66],
                  "Temperature Unit": [67, 68],
                  "Serial Number": [69, 70],
                  "Model": [71, 72],
                  "Software Revision": [73, 74]}
        statuscodes = dict()
        statuscodes["Operating State"] = {
            0: "Idling - ready to start",
            2: "Starting",
            3: "Running",
            5: "Stopping",
            6: "Error Lockout",
            7: "Error",
            8: "Helium Cool Down",
            9: "Power Related Error",
            15: "Recovered from Error",
        }
        statuscodes["Compressor State"] = {0: "Off", 1: "On"}
        statuscodes["Warning State"] = {
            -0: "No warnings",
            -1: "Coolant In Temp High",
            -2: "Coolant In Temp Low",
            -4: "Cooling Out Temp High",
            -8: "Cooling Out Temp Low",
            -16: "Oil Temp High",
            -32: "Oil Temp Low",
            -64: "Helium Temp High",
            -128: "Helium Temp Low",
            -256: "Low Pressure Low",
            -512: "Low Pressure High",
            -1024: "High Pressure High",
            -2048: "High Pressure Low",
            -4096: "Delta Pressure High",
            -8192: "Delta Pressure Low",
            -16384: "Motor Current Low",
            -32768: "Three Phase Error",
            -65536: "Power Supply Error",
            -131072: "Static Pressure High",
            -262144: "Static Pressure Low",
            -524288: "Cold Head Motor Stall",
            -1048576: "Coolant In Sensor Problem",
            -2097152: "Coolant Out Sensor Problem",
            -4194304: "Helium Sensor Problem",
            -8388608: "Oil Sensor Problem",
            -16777216: "High Pressure Sensor Problem",
            -33554432: "Low Pressure Sensor Problem",
            -67108864: "Motor Current Sensor Problem",
            -134217728: "Motor Current High",
            -268435456: "Inverter Error",
            -536870912: "Driver Communication Loss",
            -1073741824: "Inverter Communication Loss"
        }
        statuscodes["Alarm State"] = statuscodes["Warning State"]
        statuscodes["Pressure Unit"] = {0: "psi", 1: "bar", 2: "kPa"}
        statuscodes["Temperature Unit"] = {0: "F", 1: "C", 2: "K"}
        statuscodes["Model Major"] = {
            1: "8", 2: "9", 3: "10", 4: "11", 5: "28"}
        statuscodes["Model Minor"] = {1: "A1",
                                      2: "01",
                                      3: "02",
                                      4: "03",
                                      5: "H3",
                                      6: "I3",
                                      7: "04",
                                      8: "H4",
                                      9: "05",
                                      10: "H5",
                                      11: "I6",
                                      12: "06",
                                      13: "07",
                                      14: "H7",
                                      15: "I7",
                                      16: "08",
                                      17: "09",
                                      18: "9C",
                                      19: "10",
                                      20: "1I",
                                      21: "11",
                                      22: "12",
                                      23: "13",
                                      24: "14"}

        # Iterate through all keys and return the data in a usable format.
        # If there is an error in the string format, print the
        # error to logs, return an empty dictionary, and flag the data as bad
        data = {}
        data["datetime"] = datetime.datetime.now().isoformat()
        try:
            for key in keyloc.keys():
                locs = keyloc[key]
                wkrBytes = bytes([rawdata[loc] for loc in locs])

                # four different data formats to unpack
                # Big endian unsigned integer 16 bits
                if key in [
                    "Operating State",
                    "Compressor State",
                    "Pressure Unit",
                    "Temperature Unit",
                    "Serial Number",
                ]:
                    state = struct.unpack(">H", wkrBytes)[0]
                    try:
                        data[key] = statuscodes[key][state]
                    except:
                        data[key] = state
                # 32bit signed integer which is actually stored as a 32bit IEEE float (silly)
                elif key in ["Warning State", "Alarm State"]:
                    state = int(struct.unpack(">f", wkrBytes)[0])
                    try:
                        data[key] = ""
                        for status in statuscodes[key].keys():
                            if (abs(state) & abs(status)):
                                data[key] += statuscodes[key][status] + ":"
                        if (not data[key]):
                            data[key] = statuscodes[key][-0.0]
                        data[key] = data[key].rstrip(":")
                    except:
                        data[key] = state
                # 2 x 8-bit lookup tables
                elif key in ["Model"]:
                    model_major = struct.unpack(
                        ">B",  bytes([rawdata[locs[0]]]))[0]
                    model_minor = struct.unpack(
                        ">B", bytes([rawdata[locs[1]]]))[0]
                    try:
                        data[key] = statuscodes["Model Major"][model_major] + \
                            statuscodes["Model Minor"][model_minor]
                    except:
                        data[key] = str(model_major) + "_" + str(model_minor)
                elif key in ["Software Revision"]:
                    version_major = struct.unpack(
                        ">B", bytes([rawdata[locs[0]]]))[0]
                    version_minor = struct.unpack(
                        ">B", bytes([rawdata[locs[1]]]))[0]
                    data[key] = str(version_major) + "." + str(version_minor)
                # 32 bit Big endian IEEE floating point
                else:
                    data[key] = struct.unpack(">f", wkrBytes)[0]

            data_flag = False

        except:
            data_flag = True
            print(
                "Compressor output could not be converted to numbers."
                "Skipping this data block. Bad output string is {}".format(
                    rawdata)
            )

        return data_flag, data

    def __del__(self):
        """
        If the PTC class instance is destroyed, close the connection to the ptc.
        """
        self.comm.close()


def main():
    parser = argparse.ArgumentParser(
        description='Dump Cryomech Data', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--ip', type=str,
                        help='ip of cryomech device')
    parser.add_argument('--port', type=int, default=502,
                        help='port for ModBusTCP')

    args = parser.parse_args()
    ptc = PTC(ip_address=args.ip, port=args.port)
    print(ptc.get_data()[1])


if __name__ == "__main__":
    main()

```

**Comment by JakeSpisak** [comment]
Okay great, if you'd like I can move it into socs, combine it with my on/off code, and test it on our compressors.

**Comment by gdevenyi** [comment]
I'm aok with you going forward with the porting if you have the time.

**Comment by mhasself** [comment]
It would be good to close out this PR somehow... after talking with @BrianJKoopman we would like to propose that
* @JakeSpisak create an issue to remind us that he should incorporate the key improvements from this PR into the Agent code.
* We close this PR without merging, but with many thanks to @gdevenyi .

A couple of things to be aware of, in terms of OCS integration:
* Use of field names that match the manual is a good idea.  But we don't allow spaces in field names (as of recently), so e.g. change "Helium" not to "Helium Temp" but rather to "Helium_Temp".
* Perhaps hold off on converting the enumerator fields (such as Warning State) to strings -- these are not terribly easy for us to handle downstream.  A better model for OCS is probably to have a separate, slow feed for warnings and alarms, with one field for each Warning/Alarm bit, (e.g. "High Pressure High") and have those transition from 0 to 1/2 when a warning/alarm is detected.

Does that make sense?

**Comment by JakeSpisak** [comment]
Sure, I just created the issue

> It would be good to close out this PR somehow... after talking with @BrianJKoopman we would like to propose that
> 
> * @JakeSpisak create an issue to remind us that he should incorporate the key improvements from this PR into the Agent code.
> * We close this PR without merging, but with many thanks to @gdevenyi .
> 
> A couple of things to be aware of, in terms of OCS integration:
> 
> * Use of field names that match the manual is a good idea.  But we don't allow spaces in field names (as of recently), so e.g. change "Helium" not to "Helium Temp" but rather to "Helium_Temp".
> * Perhaps hold off on converting the enumerator fields (such as Warning State) to strings -- these are not terribly easy for us to handle downstream.  A better model for OCS is probably to have a separate, slow feed for warnings and alarms, with one field for each Warning/Alarm bit, (e.g. "High Pressure High") and have those transition from 0 to 1/2 when a warning/alarm is detected.
> 
> Does that make sense?

**Comment by BrianJKoopman** [comment]
Closing per the comment above. Continued discussion in https://github.com/simonsobs/socs/issues/88.

**Pull request closed without merging**
