### PR TITLE
hwp-pcu: more robust get_status

### PR DESCRIPTION
**Pull request by ykyohei**
Make status check of hwp-pcu more robust

## Description
We had issue in the robustness of get_status in precious PR https://github.com/simonsobs/socs/pull/600 
Improved the robustness of the get_status by improving the read method and adding the clear_buffer.

## How Has This Been Tested?
Tested by phase compensation unit in UTokyo.
I would appreciate it if @17-sugiyama could double check.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ykyohei** [comment]
I think `PCU.relay_off(0)` is supposed to add `>relay off 0 \n\r` in buffer, 
and `PCU.relay_read(0)` is supposed to add `>relay read 0 \n\r off \n\r` in buffer.
so we read two times in `PCU.relay_read`

**Comment by 17-sugiyama** [comment]
Sorry for the confusion. Sending commands and reading status are perfectly working with this current script.

**Review by 17-sugiyama — APPROVED** [review]
This perfectly works with UTokyo lab setup -- stable status reading and command sending.

**Review by jlashner — APPROVED** [review]
Hi Kyohei, this looks good to me for now. Eventually (soon) there are a few changes we'll need to make to the agent, in order to:
- make sure callback / errbacks are called from the reactor thread
- make sure only dicts are saved to session.data for tasks

but that can be a separate PR. I may do that for all "restructured" agents at the same time.

**Comment by ykyohei** [comment]
Thank you, can you allow me to merge this?
@jlashner

**Pull request merged**
