### PR TITLE
Wiregrid Actuator Agent: Add 'position' data in `session.data`

### PR DESCRIPTION
**Pull request by d-hoshino2626**
## Description

I added 'position' data, which means the wiregrid is in the view of the telescope (`'inside'`) or out of the view (`'outside'`), in `session.data`.

## Motivation and Context

This change enables to monitor the location of the wiregrid easily.

## How Has This Been Tested?

no test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by BrianJKoopman — APPROVED** [review]
This looks good to me, thanks for moving this over from runlib. Any plans to test before we squash and merge?

**Comment by d-hoshino2626** [comment]
Actually, I have no plans to test it because there is no hardware available in Kyoto. However, it might be possible to test it with software, for example, by streaming fake data and observing its response.

**Comment by BrianJKoopman** [comment]
> Actually, I have no plans to test it because there is no hardware available in Kyoto.

Can we coordinate a test at the site during the sun avoidance window? I'd be happy to help with that.

**Comment by d-hoshino2626** [comment]
What kind of test will you do? This PR just add new information to the session.data so I think we have no nessecities to test mechanically..

**Comment by BrianJKoopman** [comment]
> What kind of test will you do?

I was thinking just running the updated agent and inserting/ejecting the wiregrid while checking the reported position makes sense. But maybe this is as simple as you say if one is familiar with which limit switch is which.

**Comment by d-hoshino2626** [comment]
Thanks for explanation! As you say, it would be safer to test. Can you coordinate it? It's just inserting and ejecting, so it takes about 10mins, I think.

**Comment by BrianJKoopman** [comment]
I just tested this, at least partially, on satp1. 'inside' and 'outside' position reporting worked well. All I did during the test was insert then eject the wiregrid.

I did note, however, that during motion the `insert()` and `eject()` tasks hold the lock throughout motion, so position information is not updated during motion. This means it'll be important to check the timestamp is recent enough to be confident of the position when checking the position in sorunlib.

I wasn't able to put it in an 'unknown' position state, as I didn't know how to move the wiregrid into a position that wasn't fully insert or fully ejected.

Let me know what you think of the test and if you think I should test anything else.

**Comment by d-hoshino2626** [comment]
Great thanks! There is a way to move the wiregrid into a half way position, but this is a little tricky and I don't think we necessarily need to test 'unknown' position status. In my opinion, your test is sufficient!

**Review by BrianJKoopman — APPROVED** [review]

**Pull request merged**
