### PR TITLE
Remove large data structures from IV session data

### PR DESCRIPTION
**Pull request by jlashner**
There are a couple of large data structures stored in the session.data of `take_iv`. I'm concerned this is a potential location for the [data leak seen in the controllers](https://github.com/simonsobs/daq-discussions/discussions/59), so I think it's worth testing with these removed.

## Description

Removes large objects from take_iv session.data

## Motivation and Context
Potentially addresses [data leak seen in the pysmurf controllers](https://github.com/simonsobs/daq-discussions/discussions/59)

## How Has This Been Tested?
Not tested yet.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by BrianJKoopman — COMMENTED** [review]
Do you have a method to test this at site without exploratory merges to `main`?

**Comment by jlashner** [comment]
Ya, I think I'll have some time to test this on satp3 today.

**Comment by BrianJKoopman** [comment]
Any update here after testing?

**Comment by BrianJKoopman** [comment]
Given #669, do we still want to move forward on this?

**Comment by jlashner** [comment]
Nope, https://github.com/simonsobs/socs/pull/669 already implements this.

**Pull request closed without merging**
