### PR TITLE
Lakeshore425 Agent Suggestions

### PR DESCRIPTION
**Pull request by BrianJKoopman**
Just a few last suggestions on the Lakeshore425 Agent.
- Apply the param decorator to all tasks/processes.
- Add the Agent docs to the documentation page.
- Add the `any_command` output to `session.data` for inspection on the Client end.

@ykyohei, if these changes look alright to you we can merge into your branch, then merge #221. These are mostly documentation changes, but also testing the tasks/processes with new param decorators would be good, but I don't expect any major issues there.

Happy to answer any questions about any of the changes.

### CODE REVIEW

**Comment by ykyohei** [comment]
Thank you very much for all your corrections.
I was testing the agent but the 'acq' does not start properly now and I don't know why this is happening.

Before your corrections
`ls425_1                  | 2022-01-07T23:26:47+0000 startup-op: launching init_lakeshore
ls425_1                  | 2022-01-07T23:26:47+0000 start called for init_lakeshore
ls425_1                  | 2022-01-07T23:26:47+0000 init_lakeshore:0 Status is now "starting".
ls425_1                  | 2022-01-07T23:26:47+0000 init_lakeshore:0 Status is now "starting".
ls425_1                  | 2022-01-07T23:26:47+0000 LSCI,MODEL425,LSA228E,1.3
ls425_1                  | 2022-01-07T23:26:47+0000 Initialized Lakeshore module: <Lakeshore425.LakeShore425 object at 0x7f0c07fa1130>
ls425_1                  | 2022-01-07T23:26:47+0000 start called for acq
ls425_1                  | 2022-01-07T23:26:47+0000 acq:1 Status is now "starting".
ls425_1                  | 2022-01-07T23:26:47+0000 init_lakeshore:0 Lakeshore module initialized.
ls425_1                  | 2022-01-07T23:26:47+0000 init_lakeshore:0 Status is now "done".
ls425_1                  | 2022-01-07T23:26:47+0000 acq:1 Status is now "running".`

After your corrections
`ls425_1                  | 2022-01-07T23:26:23+0000 startup-op: launching init_lakeshore
ls425_1                  | 2022-01-07T23:26:23+0000 start called for init_lakeshore
ls425_1                  | 2022-01-07T23:26:23+0000 init_lakeshore:0 Status is now "starting".
ls425_1                  | 2022-01-07T23:26:23+0000 init_lakeshore:0 Status is now "starting".
ls425_1                  | 2022-01-07T23:26:23+0000 LSCI,MODEL425,LSA228E,1.3
ls425_1                  | 2022-01-07T23:26:23+0000 Initialized Lakeshore module: <socs.Lakeshore.Lakeshore425.LakeShore425 object at 0x7f12b8a175e0>
ls425_1                  | 2022-01-07T23:26:23+0000 auto_acq True
ls425_1                  | 2022-01-07T23:26:23+0000 start called for acq
ls425_1                  | 2022-01-07T23:26:23+0000 init_lakeshore:0 Lakeshore module initialized.
ls425_1                  | 2022-01-07T23:26:23+0000 init_lakeshore:0 Status is now "done".`

**Comment by BrianJKoopman** [comment]
Interesting, thanks for testing. I'm working on a way to test that functionality locally without a 425. In the meantime, does the acq process start if you call it directly?

```
from ocs.ocs_client import OCSClient
client = OCSClient('425-agent')
client.acq.start()
```

**Comment by ykyohei** [comment]
This may not be equivalent but I tested by ocs_util (v0.8.0)
acq doesn't do anything, operational_status crashed.
Before your correction, operational status was also working.

```
ls = matched_client.MatchedClient('LS425', args=['--site-http=http://crossbar:8001/call'])
status, msg, session = ls.acq()
print(status)
print(session)
print(msg)
```
> 0
> {}
> No session active.

```
status, msg, session = ls.operational_status()
print(status)
print(msg)
print(session)
```

> 0
> Operation "operational_status" is currently not running (FAILED).
> {'session_id': 3, 'op_name': 'operational_status', 'op_code': 6, 'status': 'done', 'success': False, 'start_time': 1641869463.3639085, 'end_time': 1641869463.475, 'data': {}, 'messages': [[1641869463.3639085, 'Status is now "starting".'], [1641869463.4724352, "CRASH: [Failure instance: Traceback: <class 'IndexError'>: list index out of range\n/usr/lib/python3.8/threading.py:932:_bootstrap_inner\n/usr/lib/python3.8/threading.py:870:run\n/usr/local/lib/python3.8/dist-packages/twisted/_threads/_threadworker.py:47:work\n/usr/local/lib/python3.8/dist-packages/twisted/_threads/_team.py:181:doWork\n--- <exception caught here> ---\n/usr/local/lib/python3.8/dist-packages/twisted/python/threadpool.py:238:inContext\n/usr/local/lib/python3.8/dist-packages/twisted/python/threadpool.py:254:<lambda>\n/usr/local/lib/python3.8/dist-packages/twisted/python/context.py:118:callWithContext\n/usr/local/lib/python3.8/dist-packages/twisted/python/context.py:83:callWithContext\nLS425_agent.py:165:operational_status\n/app/socs/socs/Lakeshore/Lakeshore425.py:51:get_op_status\n]"], [1641869463.475, 'Status is now "done".']]}

**Comment by BrianJKoopman** [comment]
A couple of things:

> This may not be equivalent but I tested by ocs_util (v0.8.0) acq doesn't do anything, operational_status crashed.
> 
> ```
> ls = matched_client.MatchedClient('LS425', args=['--site-http=http://crossbar:8001/call'])
> status, msg, session = ls.acq()
> print(status)
> print(session)
> print(msg)
> ```

Since `acq` is a Process, `ls.acq()` is equivalent to just `ls.acq.status()`. With Tasks it would be equivalent to `ls.acq.start()` then `ls.acq.status()`. So your test didn't actually try to start the Process.

However, I did figure out the bug that we're running into on startup. I've recorded it here and will patch it in ocs soon: https://github.com/simonsobs/ocs/issues/251

I'll commit a fix that'll work for us here in this PR momentarily.

I'm unsure what happened in your call to `operational_status()` though. It looks like an IndexError. Do you know what the response to "OPST?" would have been in this instance?

**Comment by BrianJKoopman** [comment]
Alright, fixed in 2248e7cd5295b26086eb584db88effb66adc276b. @ykyohei can you test startup again?

**Comment by ykyohei** [comment]
Thank you, now 425 agent startup correctly
Also, I fixed the bug of operational status fbe524e5d1db23029288af761b0beb706b1a5d85.
I'll merge this, then merge #221.

**Pull request merged**
