### PR TITLE
Add new status log fields from beta software

### LINKED ISSUE #47: Bluefors logs agent fails when status data is logged
In the new, beta version of the bluefors software, the bluefors log agent throws an error when status data from the compressor, pumps, FSE, ect. is logged (see picture). 
bluefors_logs

Specifically, the error is
 `ocs-bluefors_1  | 2020-02-24T19:22:15+0000 acq:0 Crash in thread: [Failure instance: Traceback: <class 'AttributeError'>: 'NoneType' object has no attribute 'group'
ocs-bluefors_1  | /usr/lib/python3.6/threading.py:916:_bootstrap_inner
ocs-bluefors_1  | /usr/lib/python3.6/threading.py:864:run
ocs-bluefors_1  | /usr/local/lib/python3.6/dist-packages/twisted/_threads/_threadworker.py:46:work
ocs-bluefors_1  | /usr/local/lib/python3.6/dist-packages/twisted/_threads/_team.py:190:doWork
ocs-bluefors_1  | --- <exception caught here> ---
ocs-bluefors_1  | /usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py:250:inContext
ocs-bluefors_1  | /usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py:266:<lambda>
ocs-bluefors_1  | /usr/local/lib/python3.6/dist-packages/twisted/python/context.py:122:callWithContext
ocs-bluefors_1  | /usr/local/lib/python3.6/dist-packages/twisted/python/context.py:85:callWithContext
ocs-bluefors_1  | bluefors_log_tracker.py:401:start_acq
ocs-bluefors_1  | bluefors_log_tracker.py:313:read_and_publish_logs
ocs-bluefors_1  | bluefors_log_tracker.py:241:_parse_multi_value_log
ocs-bluefors_1  | ]
ocs-bluefors_1  | 2020-02-24T19:22:15+0000 acq:0 Status is now "done".`

The status log that is the source of the error is here. It is not obvious to me from the error message what the problem is. 
[Status 20-02-24.log](https://github.com/simonsobs/socs/files/4246545/Status.20-02-24.log)

### PR DESCRIPTION
**Pull request by BrianJKoopman**
## Description

Adds the new fields present in status logs output by the new beta software for the DR.

## Motivation and Context

New status fields weren't in the regex patterns.

fixes #47

## How Has This Been Tested?

Still needs testing. Either build an image, or use `grumpy.physics.yale.edu/ocs-bluefors-agent:beta`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Unless I am preparing a release, I have opened this PR onto the `develop` branch.

### CODE REVIEW

**Comment by JakeSpisak** [comment]
Thanks for the quick turnaround. The new image failed, but I checked the status file and narrowed it down to just one missing field, 'cpascale'. Otherwise everything matches

**Comment by JakeSpisak** [comment]
I also discovered the issue with our K2SO system: it has an entire new class of field names (I don't know why I just now thought of actually looking in the bluefors agent code to discover this). The new names to add are: nxdsf, nxdsct, nxdst, nxdsbs, nxdstrs.

**Comment by JakeSpisak** [comment]
It's this 'nXDS series scroll pump' model, I guess it is different than what we have in the highbay and what is at other institutions

**Comment by BrianJKoopman** [comment]
Ah, great. I just added all of these missing fields and rebuilt the image. To test run `docker pull grumpy.physics.yale.edu/ocs-bluefors-agent:beta`, then bring up the container as usual.

**Comment by JakeSpisak** [comment]
Oddly the new image didn't work, but I checked and all the fields are correct. So I'm not sure what's going on. Here are the two status files from K2SO and SAT1. 
[Status_20-10-22_sat1.log](https://github.com/simonsobs/socs/files/5424336/Status_20-10-22_sat1.log)
[Status_20-10-22_k2so.log](https://github.com/simonsobs/socs/files/5424337/Status_20-10-22_k2so.log)

**Comment by BrianJKoopman** [comment]
Right, sorry, small bug still existed. It loops over all the regex patterns and looks for a match. Patched to skip non-matching patterns.

**Comment by BrianJKoopman** [comment]
New patch verified at UCSD on both k2so and sat1 systems. Merging.

**Pull request merged**
